name: 'my_first_dbt_project_on_snowflake'
version: '1.0'
config-version: 2

profile: 'my_first_dbt_project_on_snowflake'

model-paths: ["models"]
seed-paths: ["seeds"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  my_first_dbt_project_on_snowflake:
    +materialized: view
    staging:
      +schema: staging
    marts:
      +schema: marts
