name: dbt_hol_project
version: 1.0
config-version: 2

profile: default

model-paths: ["models"]

models:
  dbt_hol_project:
    staging:
      +schema: public
      +materialized: view
    marts:
      +schema: public
      +materialized: table
