dbt_hol:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: ZBYCHSB-XQ56074
      user: SUNITHA
      password: "SRdhanamjayamApril_2022"
      role: ACCOUNTADMIN
      warehouse: DBT_POC_WH
      database: DBT_POC_DB
      schema: DBT_POC_SCHEMA
      threads: 4
      client_session_keep_alive: false
