version: 2

sources:
  - name: public_source
    description: "Raw data source for the HOL dbt project stored in DBT_HOL_DEV.PUBLIC"
    database: DBT_HOL_DEV
    schema: PUBLIC
    tables:
      - name: raw_orders
        description: "Manually created raw orders table used for PoC."
