mytrial:
  target: dev
  outputs:
    dev:
      type: snowflake
      role: ACCOUNTADMIN
      warehouse: COMPUTE_WH
      database: DBT_POC_DB
      schema: DBT_POC_SCHEMA
      account: ' '
      user: ' '
